### ISSUE TITLE
Port conflict

### ISSUE THREAD

**Issue by aranjmiller** [iamkroot/trakt-scrobbler#106]
I have a port conflict. I can not see it listed anywhere but it seems trakts is using port 8080. I have a conflict on this port with another program. I did not see port in the config settings. Is it possible to change the port that trakts uses?

**Comment by iamkroot** [comment]
Trakt scrobbler doesn't create any web servers of its own. But the conflict you see here is most likely because of VLC. It uses `8080` by default to set up its web interface. All you need to do is change that value at `Preferences -> All -> Input/Codecs -> HTTP Server Port` and the scrobbler _should_ automatically pick it up after a restart.

**Comment by aranjmiller** [comment]
Thank you.
