### ISSUE TITLE
[Config file] switch to toml?

### ISSUE THREAD

**Issue by ahmubashshir** [iamkroot/trakt-scrobbler#121]
IMO, using toml in config file is better as toml are more readable and provides better structure, and safer than [yaml](https://noyaml.com/).

**Comment by iamkroot** [comment]
This repo did use TOML in the beginning. Had to migrate to YAML with v1 release since I started using [`confuse`](https://github.com/beetbox/confuse) for config management, and it doesn't support anything other than YAML.

Secondly, even if it did, there's not much incentive to migrating. Since we anyway have the `trakts config` command as a wrapper over the config file, it doesn't matter what the underlying format is. Have you faced any issues specifically related to YAML while using the scrobbler? If so, we can discuss those.

**Comment by ahmubashshir** [comment]
I couldn't set `players.*.poll_interval` with `trakts config set` to fraction, I had to edit config.

**Comment by iamkroot** [comment]
> I couldn't set `players.*.poll_interval` with `trakts config set` to fraction

Woah, do you really care if the trakt servers are off by more than a second? It should really not be needed to be using fractions in `poll_interval`. Although, I do agree on the general issue here - the `trakts config set` command assumes that the new value has the same (python) type as the old one. But I don't believe it is really worth it to be adding support for this. As you mentioned, editing the config file manually should be enough in most cases. If a user really does come up with a genuine need for changing types, we can investigate further (I was thinking of using the confuse templates for type validation, but might be difficult to collect them centrally).

**Comment by iamkroot** [comment]
> we can introduce `players.poll_interval` as default value unless `players.*.poll_interval` is set for that specific player.

It is not necessary for every player monitor to use polling for getting player info (for instance, mpv does not use it as a primary source, but only for supporting some wrappers that might not close the file cleanly). So it doesn't make sense to have the `poll_interval` inherited from `players` directly.

**Comment by iamkroot** [comment]
Closing for now. We'll consider this if serious issues come up with the YAML format that affect us.
