### ISSUE TITLE
[BUG?] OAuth Timestamps Issues

### ISSUE THREAD

**Issue by rfvgyhn** [iamkroot/trakt-scrobbler#166]
I'm working on a self-hosted version of trakt and am testing this scrobbler against my API. I'm running into an issue when checking the expiry of the token retrieved from `/oauth/device/token` though and I'm not sure if it's an issue on my end or not.

1. Does trakt not use UTC in their timestamps or should `trakt_auth.token_expires_at()` and `trakt_auth.is_token_expired()` be using `dt.utcfromtimestamp()` and `dt.utcnow()`?
2. What's the design choice of using `self.token_expires_at() - dt.now() < self.TOKEN_EXPIRY_BUFFER` instead of something like `self.token_expires_at() <= dt.now()`? Currently, if the token's `expires_in` field is less than `86400` (one day), `is_token_expired()` always returns true even if the token isn't expired. Trakt currently returns a value of `7776000` so the issue doesn't arise when using trakt's api.

**Comment by iamkroot** [comment]
> I'm working on a self-hosted version of trakt

Wow, amazing! All the best friend!

> 1\. Does trakt not use UTC in their timestamps

Yeah, it does. Notice that we do use `dt.utcfromtimestamp()` in https://github.com/iamkroot/trakt-scrobbler/blob/ce94a072ca9e2b2013be56405dca2e7398ecaedf/trakt_scrobbler/trakt_interface.py#L127

We should probably do the same in the auth code.


> 2\. What's the design choice of using `self.token_expires_at() - dt.now() < self.TOKEN_EXPIRY_BUFFER`

Ah, this is a remnant of the design from the very [first commit](https://github.com/iamkroot/trakt-scrobbler/blob/34b34be975486e403a3e2b2a523f7c17bc9b5bfb/trakt_scrobbler/trakt_interface.py#L135) :P. Essentially, we only checked `token.is_expired()` _at startup_ and cached the token forever, never checking when it expires. This would obviously cause problems when the token does expire, so I worked around it by assuming that the scrobbler gets restarted at least once a day (in the first commit, it was actually 1 hour, which is definitely bad :P). That way, when our app starts and sees less than a day remaining before expiry, we refresh preemptively.

This _also_ hides the bug in the previous point, since UTC/local timezones difference doesn't matter if we are anyway refreshing one day in advance.

But this should probably be fixed. Currently, we _do_ check for expiry before every call to trakt, so don't need a buffer and can refresh when the token really expires.
