### ISSUE TITLE
[Installation] Failed to autoload value for VLC installed with snap

### ISSUE THREAD

**Issue by b-luu** [iamkroot/trakt-scrobbler#171]
### System Info
* Operating system and version: Ubuntu 21.10 (minimal)
* Media Player and version: VLC 3.0.16
* Python version: 3.10.1

### Description
`vlcrc` file wasn't found
=> autoload of VLC configuration could not work.

### Reason
VLC was installed from the store with Snap...
So the `vlcrc` isn't located at `$HOME/.config/vlc/` but at `$HOME/snap/vlc/common/`

### Work-around
Create a symbolic link:
```
ln -s "$HOME/snap/vlc/common/vlcrc" "$HOME/.config/vlc/vlcrc"
```
For future reference, if you get the same error but you're vlcrc isn't in `$HOME/snap/vlc/common/` either, you should be able to `find` it with:
```
find ~ -name vlcrc
```
And then you can simply replace the first path of the `ln -s` command above, with the one you actually found.

### Needed (long-term) solution
Detect snap install and point to `$HOME/snap/vlc/common/` in that case

### Command line output

```
Failed to autoload value from PosixPath('/home/<myhome>/.config/vlc/vlcrc'): File not found
```

### Log file

<details>
  <summary>Click to see log contents</summary>  
<p>

```
2022-01-02 17:46:12,545 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2022-01-02 17:46:12,680 - INFO - MainThread - scrobbler - Started scrobbler thread.
2022-01-02 17:46:12,687 - DEBUG - MainThread - monitor - Failed to autoload value from PosixPath('/home/<myhome>/.config/vlc/vlcrc'): File not found
2022-01-02 17:46:12,688 - ERROR - MainThread - monitor - Config value autoload failed for vlc.
2022-01-02 17:46:12,688 - WARNING - MainThread - main - Could not start monitor for vlc
```
</p>
</details>

### PS
I wanted to add the work-around in the wiki ([VLC player setup section](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#vlc) directly) but didn't find an easy way to contribute to the documentation (without having to fork and open a PR)

### Thanks
Thanks for this tool, it's great !! And the code is nicely written, it's a pleasure to navigate. Nice work !!

**Comment by iamkroot** [comment]
Thanks for digging so deep into it and for making a detailed bug report! Simplest solution seems to be to add the snap dir to the list of potential config paths. I'll do just that.

However, do note that the autoload is just a bonus feature. If the app can't find the config files due to non-standard paths, you can always set the values manually using `trakts config set players.<player_name>.<key> <value>`.

To find out the fields you need to specify, take a look at the [`config_default.yaml`](https://github.com/iamkroot/trakt-scrobbler/blob/f9725a78776a03e8f80504bcff63697fd9c2e9f6/trakt_scrobbler/config_default.yaml#L50) file (all entries with `auto-detect` for your player need to be filled in manually). Since you don't frequently change the options in your media player (if at all), this should be fine.

I should probably mention this in the wiki too.

**Comment by iamkroot** [comment]
> I wanted to add the work-around in the wiki ([VLC player setup section](https://github.com/iamkroot/trakt-scrobbler/wiki/Players-Setup#vlc) directly) but didn't find an easy way to contribute to the documentation (without having to fork and open a PR)

That is mostly by design; I prefer to have the potential contribution discussed here as an issue first, before you (or anyone else) commits their time and effort into a possibly misguided change.
