### ISSUE TITLE
[BUG] Adding to whitelist through tool's interfaces resolves network drives on Windows

### ISSUE THREAD

**Issue by ixSci** [iamkroot/trakt-scrobbler#176]
I have a bunch of network drives mapped to the samba shares. I use these drives to play videos with VLC. 
So I tried to add my disks to the whitelist but instead network locations were added. Here is an example:
```
trakts.exe whitelist add "W:\"
\\192.168.1.2\Movies\</> added to whitelist.
```
And then it proceeds to not process my files because in VLC they are from `W:\`, not `\\192.168.1.2\Movies\`. Directly adding my drives to `config.yaml` works, though. 

**Desktop:**
 - OS and Version: Windows 11
 - Python Version: 3.10.2

**Comment by iamkroot** [comment]
I see. This is happening because we have a `resolve()` call on the given path:
https://github.com/iamkroot/trakt-scrobbler/blob/fd476d12db937c5ea76039c9ec1b7dcb076ce67f/trakt_scrobbler/commands/whitelist.py#L51

I guess we don't really need that, the `absolute()` path ought to be enough. Will make the change.
