### ISSUE TITLE
[BUG] Does not start with python-cleo 1.0.0a5

### ISSUE THREAD

**Issue by wazabees** [iamkroot/trakt-scrobbler#210]
**Describe the bug**
`cannot import name 'Application' from 'cleo' (/usr/lib/python3.10/site-packages/cleo/__init__.py)`

A clear and concise description of what the bug/error is.
trakt-scrobbler does not work if python-cleo 1.0.0a5-2 is installed.

**Desktop (please complete the following information):**
Arch linux, 5.19.7-arch1-1
Python 3.10.6
mpv 0.34.1
trakt-scrobbler 1.5.0-1 from the AUR

**To Reproduce**
Install latest python-cleo and try to run trakt-scrobbled.

**Log file**
Unable to run "trakts log open" or "trakts log path" now.

**Comment by iamkroot** [comment]
Sorry, this is not a scrobbler bug. We explicitly state that we depend on cleo v0.8 in our pyproject.toml file. Installing other versions could cause breakage.

In this case, I would ask why is Arch Linux upgrading their package to an alpha version. Till cleo maintainers release a stable version, it would not be worthwhile to make the effort of migrating.

For a solution, I suggest using the venv approach instead of the AUR package. You can find the installation instructions in the github wiki.

**Comment by wazabees** [comment]
Thank you for the explanation! ;)

**Comment by ahmubashshir** [comment]
@wazabees test #216 please.

**Comment by wazabees** [comment]
> @wazabees test #216 please.

Hey @ahmubashshir - thanks for the ping! I went a different route and decided to use `pipx` instead. My hope is that I'll experience less breakage that way. ;)
