### ISSUE TITLE
[RFC] Issues about pinned setuptools

### ISSUE THREAD

**Issue by ahmubashshir** [iamkroot/trakt-scrobbler#255]
As far as I've seen, we don't depend on setuptools package in any way (is it even needed when we're using pypoetry?)

**Comment by iamkroot** [comment]
I do remember adding it manually because something broke after we moved from pipenv. Will take a look at the git history and see.

**Comment by iamkroot** [comment]
Hey @ahmubashshir I just went through #257. Turns out we need `setuptools` because `babelfish` (which itself is a dep of `guessit`) wants `pkg_resources` that hasn't been shipped with Python for a long time. Once https://github.com/Diaoul/babelfish/issues/46 is fixed, we can remove `setuptools` from our deps.

**Comment by ahmubashshir** [comment]
Diaoul/babelfish#46 got the fix in [`Diaoul/babelfish@0.6.1`](https://github.com/Diaoul/babelfish/releases/tag/0.6.1)
