### ISSUE TITLE
[BUG] trakt-scrobbler are not working with syncplay@mpv

### ISSUE THREAD

**Issue by soredake** [iamkroot/trakt-scrobbler#266]
**Describe the bug**
https://github.com/Syncplay/syncplay/issues/529

After each start `input-ipc-path` value will be different:
![изображение](https://github.com/iamkroot/trakt-scrobbler/assets/5204968/6cb5019c-a86a-4f9e-a277-917ed468fe2e)

**Desktop (please complete the following information):**
 - OS and Version: Windows 11 Pro
 - Python Version: Python 3.10.11
 - Player and Version: MPV.net from microsoft store

**To Reproduce**

1. Install syncplay, trakt-scrobbler and mpv.net from microsoft store
2. `trakts config set players.monitored mpv syncplay@mpv; trakts config set players.mpv.ipc_path \\.\pipe\mpvsocket`
3. Set `--input-ipc-server=\\.\pipe\mpvsocket` as player arguments in syncplay for mpv.net
4. Join room, add some media file.
5. See error in log file

**Log file**

<details><summary>Click to see log contents</summary> 
<p>

```
2023-11-24 19:42:37,245 - INFO - MainThread - scrobbler - Started scrobbler thread.
2023-11-24 19:42:37,272 - INFO - MainThread - monitor - Started monitor for mpv
2023-11-24 19:42:37,274 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.
2023-11-24 19:42:37,279 - DEBUG - MainThread - monitor - Autoloaded syncplay@mpv ipc_path = \\\\.\\pipe\\mpvsocket
2023-11-24 19:42:37,279 - INFO - MainThread - monitor - Started monitor for syncplay@mpv
2023-11-24 19:42:37,280 - INFO - syncplay@mpv - mpv - Unable to connect to MPV. Check ipc path.
```
</p>
</details>

I think the problem lies in syncplay, when i set `--input-ipc-server=\\.\pipe\mpvsocket` as player argument it results in double `input-ipc-server`
![изображение](https://github.com/iamkroot/trakt-scrobbler/assets/5204968/7b40416f-26e6-4d0e-a2d8-37fc26eebcbe)

Maybe related https://github.com/Syncplay/syncplay/issues/529

**Comment by iamkroot** [comment]
Yeah, this looks more like a syncplay bug.

I can think of some ways to go forward-
1. Making syncplay respect the user config (as suggested in https://github.com/Syncplay/syncplay/issues/529) is definitely the best way to do it IMO. This was already working in previous versions of syncplay (we don't clash with their code) and should be relatively easy to fix from their end.
2. Bypass the IPC server entirely- write a MPV plugin in Lua/JS that listens for the events we care about (like start, pause, etc.), and sends them over to our monitor via IPC (essentially reinventing the IPC server)
3. In general, I have been considering implementing a MPRIS monitor - this would allow us to support any player that exposes current media info via that protocol. Main issue would be ensuring we get all the needed info we care about (file paths, etc.). Another big one is that this is also Linux-only, so need to find a Windows equivalent.

Both 2 and 3 are pretty big projects, I'd rather try getting https://github.com/Syncplay/syncplay/issues/529 resolved first.

**Comment by soredake** [comment]
Without `--input-ipc-server=\\.\pipe\mpvsocket`:
![image](https://github.com/iamkroot/trakt-scrobbler/assets/5204968/f2ee3425-72f6-4d8c-92bc-88e5d2846f53)

With `--input-ipc-server=\\.\pipe\mpvsocket`:
![image](https://github.com/iamkroot/trakt-scrobbler/assets/5204968/effeeeec-709b-45f7-905f-69e185b969f5)


Log remains the same:
```
2024-01-01 19:27:24,929 - DEBUG - MainThread - notifier - Notifications enabled for categories: exception, misc, scrobble.pause, scrobble.resume, scrobble.start, scrobble.stop, trakt
2024-01-01 19:27:25,190 - INFO - MainThread - scrobbler - Started scrobbler thread.
2024-01-01 19:27:25,202 - INFO - MainThread - monitor - Started monitor for mpv
2024-01-01 19:27:25,203 - INFO - mpv - mpv - Unable to connect to MPV. Check ipc path.
2024-01-01 19:27:25,205 - DEBUG - MainThread - monitor - Autoloaded syncplay@mpv ipc_path = \\\\.\\pipe\\mpvsocket
2024-01-01 19:27:25,205 - INFO - MainThread - monitor - Started monitor for syncplay@mpv
2024-01-01 19:27:25,206 - INFO - syncplay@mpv - mpv - Unable to connect to MPV. Check ipc path.
```

**Comment by soredake** [comment]
As a workaround i set `ipc_path` to `\\.\pipe\\\.\pipe\mpvsocket` and now it works.

**Comment by iamkroot** [comment]
> Without `--input-ipc-server=\\.\pipe\mpvsocket`:
> ![image](https://private-user-images.githubusercontent.com/5204968/293599435-f2ee3425-72f6-4d8c-92bc-88e5d2846f53.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQxMzE1ODgsIm5iZiI6MTcwNDEzMTI4OCwicGF0aCI6Ii81MjA0OTY4LzI5MzU5OTQzNS1mMmVlMzQyNS03MmY2LTRkOGMtOTJiYy04OGU1ZDI4NDZmNTMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDEwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMDFUMTc0ODA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjU3NDU5MDJmZThjOGVkMzlkMzRhYTk1N2RlZDlhOWU3NWIxZWNiOTVjZDM4MDdhYTFhZGEyNjc4ODU0OWRlMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dRRgYjVax0TlFWoeS_OJr1xucET3WndQaDK4PYT4Vs8)

Wait, so when you don't provide `--input-ipc-server`, after a restart, this is shown in the Syncplay UI?

**Comment by soredake** [comment]
> this is shown in the Syncplay UI?

Not in syncplay ui, i use [this tool](https://learn.microsoft.com/en-us/sysinternals/downloads/process-explorer) to see what arguments are applied when starting mpv

**Comment by iamkroot** [comment]
ah that makes more sense. Then I'm pretty sure this is a syncplay bug- it is messing up the args somehow. Closing on our side.

**Comment by Et0h** [comment]
As per discussion at https://github.com/Syncplay/syncplay/issues/529 I have created https://github.com/Syncplay/syncplay/pull/669 that means that when the user specifies which port mpv should use it will set input-ipc-server it to socket again which should allow a second connection on that socket.

However, looking at https://github.com/iamkroot/trakt-scrobbler/blob/7eef02fcfdefb665de6a77dfba403464f024f2ff/trakt_scrobbler/player_monitors/mpv_wrappers.py it looks like some further changes will be required to get it to work reliably via trakt-scrobbler.

Firstly, if there is a Syncplay.ini or .Syncplay folder in the Syncplay folder then Syncplay will use that in preference to the file in the APPDATA folder. This is what distinguishes the installed version of Syncplay from the portable version of Syncplay.

Secondly, someone can have multiple different player entries for perplayerarguments depending on the path of the player. 
You can get the perplayerargument for the currently selected player by first looking at the value of playerpath and then use that as the key for which which perplayerargument to use.

Thirdly, it can be set as input-ipc-server rather than --input-ipc-server so just looking for --input-ipc-server might not find it.

In any case, I've now updated the Syncplay PR (https://github.com/Syncplay/syncplay/actions/runs/7756006347?pr=669) so that it will automatically create a secondary socket called mpvSyncplaySocket (AKA `\\.\\pipe\\mpvSyncplaySocket`) if no value for input-ipc-server is specified in the perPlayerArguments for that player. This should make it easier for trakt-scrobbler and other tools to support Syncplay.
