### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by onepiececomparisons** [iamkroot/trakt-scrobbler#3]
I'm fairly new at python so I'm sorry if it's a dumb question.
Does the CMD window have to be running for it work? If so, is there a way to hide it so it's not in the task bar all the time?

**Edit:** Ok I ended up understanding that I needed to restart the PC for it to start working while in the background so that is working fine now.
Unfortunately another issue remains, the episode gets added to the history twice. Any idea what's happening?

I checked the logs and everything seems to be going through twice https://i.gyazo.com/454c02a95d0900f3a30b2cedf7785fd9.png
There's only one instance of pythonw.exe on the task manager if that helps.

**Edit again:** Turns out it was because the script is listening for MPCBE and MPCHC using the same port causing it to register everything twice, I deleted the one I don't use and now works fine.
Welp looks like I figured everything out by myself lol all there's left to say is thanks for this great script man, it's super convenient. Have a nice day!

**Comment by iamkroot** [comment]
Hey there! Turns out I'm a pretty dumb person who forgot to set their own repo to watching :P, which means I didn't get any notifications about new activity. And I'm _just_ getting to know about this issue having existed, so sorry about not replying earlier! Glad to see that you're benefitting from this, and if you have any more issues, please do report them,

**Comment by cyatek** [comment]
Hey, same guy on a different account.
Since then I've been having two issues, nothing huge just minor inconveniences. I haven't tried the latest version so I apologize if you already addressed them.

So I keep my PC on at all times and I find that the script doesn't survive very long, for instance if I watch an episode day 1 morning and then another one day 2 evening, the script will have already stopped working the pythonw.exe is still in task manager it just does nothing, so basically everyday before watching episodes I have to force close it and run it again like I just restarted the PC.

Second issue, this one is really minor, if I let MPC reach the very very ending like so [https://i.imgur.com/duofwmL.png](url) the episode will somehow scrobble twice [https://i.imgur.com/P820BSW.png](url), notice that it seems that it did both at the same time but in reality the second one takes about 20 minutes to appear.

And going back to me not having tried the latest version, it's because I don't really know how to perform and update with these things ahah, do I just install everything from scratch?

**Comment by iamkroot** [comment]
For the first two issues, could you please create a new bug report, and attach the log file there? (Instructions will be provided while creating the issue)

I hadn't really considered the update problem till now. I'll try to get it included in the install script. I've made some changes to the windows installation recently, so I'm afraid you'll have to start from scratch this time. Follow these steps:
1) Clone/download this repo at some place (let's call this `Dir1`)
2) Open the current install location (`%APPDATA%\trakt-scrobbler`, aka `Dir2`)
3) Copy the `data` folder from `Dir2` to `Dir1\trakt_scrobbler` (Notice the `_`). You'll be asked to replace/skip the `sample_config.toml`, you can do either.
4) Kill `pythonw.exe`. Delete the folder at `Dir1`.
5) Run the install script.
