### ISSUE TITLE
changelog?

### ISSUE THREAD

**Issue by Hillgrove** [iamkroot/trakt-scrobbler#79]
Congratulations with your first major release.

I may be blind but I can't find the changelog anywhere.

Thanks.

**Comment by iamkroot** [comment]
> Congratulations with your first major release.

Thanks!

> can't find the changelog

Because there isn't any :sweat_smile:. I've been releasing v1 betas for a few months now, and it's all just been mixed stuff. Following semver, everything prior to this was considered unstable, and adding to that my laziness, I haven't maintained a changelog for the 0.x versions. Actually, there wasn't any user-facing versioning at all for a long time, only git commits.

To answer your question, I would sum up v1.0.0 as basically the "Stable" release, which is finally ready for consumption by end users. The core functionality hasn't changed much from before, only some new quality-of-life improvements and polishing up of the existing app. 

Notably, the installation method has been revamped to use python packaging instead of a homegrown install script, which was getting difficult to manage. Another major addition is the `trakts` command which allows the user to easily query and configure the scrobbler from the terminal. For more minute changelog, I'm gonna have to direct you to the commit messages sadly.

I should probably add this in the release description, thanks for creating the issue!
